package com.cg.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.cg.webservice.employeesoapwebserviceimpl.EmployeeSOAPWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2016-10-17T15:46:49.328+05:30
 * Generated source version: 2.6.13
 * 
 */
@WebServiceClient(name = "EmployeeSOAPWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/snsreede/Documents/EmployeeManagementWithDatabase/EmployeeManagementWithMySqlDatabase/WebContent/WEB-INF/wsdl/EmployeeService.wsdl",
                  targetNamespace = "http://webservice.cg.com/") 
public class EmployeeSOAPWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.cg.com/", "EmployeeSOAPWebServiceImplService");
    public final static QName EmployeeSOAPWebServiceImplPort = new QName("http://webservice.cg.com/", "EmployeeSOAPWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/snsreede/Documents/EmployeeManagementWithDatabase/EmployeeManagementWithMySqlDatabase/WebContent/WEB-INF/wsdl/EmployeeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeSOAPWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/snsreede/Documents/EmployeeManagementWithDatabase/EmployeeManagementWithMySqlDatabase/WebContent/WEB-INF/wsdl/EmployeeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeSOAPWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeSOAPWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeSOAPWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmployeeSOAPWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmployeeSOAPWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmployeeSOAPWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EmployeeSOAPWebService
     */
    @WebEndpoint(name = "EmployeeSOAPWebServiceImplPort")
    public EmployeeSOAPWebService getEmployeeSOAPWebServiceImplPort() {
        return super.getPort(EmployeeSOAPWebServiceImplPort, EmployeeSOAPWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeSOAPWebService
     */
    @WebEndpoint(name = "EmployeeSOAPWebServiceImplPort")
    public EmployeeSOAPWebService getEmployeeSOAPWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EmployeeSOAPWebServiceImplPort, EmployeeSOAPWebService.class, features);
    }

}
